### ISSUE TITLE
run tests

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [zeganstyl/thelema-engine#7]
`gradlew :tests:run` does not really work. Can it be fixed?

**Comment by zeganstyl** [comment]
Are you mean add gradle plugin "application" ? It gives such gradle task.
But I can't add this plugin due to incompatibility with plugin "com.android.application".

**Comment by dmitrykolesnikovich** [comment]
> But I can't add this plugin due to

that statement is too unambitious for the guy who wrote God Rays shader :)

**Comment by zeganstyl** [comment]
> > But I can't add this plugin due to
> 
> that statement is too unambitious for the guy who wrote God Rays shader :)

Haha, you are right, I will try.

**Comment by zeganstyl** [comment]
I added gradle task "run". 96c3609ceff86d97453acf5ed84a81be70dde003

Can you check and confirm that it works?

**Comment by dmitrykolesnikovich** [comment]
by the way I found excellent videos on Kotlin + Gradle topic https://www.youtube.com/channel/UC-Vhmm09W_IWKHhSg80d68w/videos

**Comment by dmitrykolesnikovich** [comment]
I'm running tests on MacOS with following log

```
dmitrykolesnikovich$ gradlew tests:run

> Configure project :
Kotlin Multiplatform Projects are an Alpha feature. See: https://kotlinlang.org/docs/reference/evolution/components-stability.html. To hide this message, add 'kotlin.mpp.stability.nowarn=true' to the Gradle properties.


The Kotlin source set androidAndroidTestRelease was configured but not added to any Kotlin compilation. You can add a source set to a target's compilation by connecting it with the compilation's default source set using 'dependsOn'.
See https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#connecting-source-sets

The Kotlin source set androidAndroidTestRelease was configured but not added to any Kotlin compilation. You can add a source set to a target's compilation by connecting it with the compilation's default source set using 'dependsOn'.
See https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#connecting-source-sets

> Task :compileKotlinJvm FAILED
e: /Users/dmitrykolesnikovich/workspace/temp/thelema-engine/src/jvmMain/kotlin/app/thelema/lwjgl3/audio/WavSound.kt: (29, 33): Unresolved reference: readNBytes

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlinJvm'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by zeganstyl** [comment]
What JDK version are you using?

**Comment by dmitrykolesnikovich** [comment]
```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```

**Comment by zeganstyl** [comment]
> ```
> java version "1.8.0_231"
> Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
> Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
> ```

Can you upgrade your JDK version?
For example to 11.

**Comment by dmitrykolesnikovich** [comment]
Migration to Java 11 fixes current problem but there is another

```
> Task :tests:run FAILED
[LWJGL] Failed to load a library. Possible solutions:
        a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
        b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib
        at org.lwjgl.system.Library.loadSystem(Library.java:162)
        at org.lwjgl.system.Library.loadSystem(Library.java:62)
        at org.lwjgl.system.Library.<clinit>(Library.java:50)
        at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97)
        at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
        at org.lwjgl.system.Callback.<clinit>(Callback.java:41)
        at app.thelema.lwjgl3.JvmApp$Companion.initializeGlfw(JvmApp.kt:305)
        at app.thelema.lwjgl3.JvmApp.<init>(JvmApp.kt:113)
        at app.thelema.lwjgl3.JvmApp.<init>(JvmApp.kt:50)
        at app.thelema.lwjgl3.MainTestJvm.main(MainTestJvm.kt:30)
```

**Comment by dmitrykolesnikovich** [comment]
I can fix it myself obviously but maybe it better to fix it on your side to make it work for everyone.

**Comment by zeganstyl** [comment]
> I can fix it myself obviously but maybe it better to fix it on your side to make it work for everyone.

Yes, I will fix it.
